"""add_offer_fields_to_product

Revision ID: 3306be9f287f
Revises: 381bf2cbe990
Create Date: 2026-09-10 15:55:55.856053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3306be9f287f'
down_revision: Union[str, Sequence[str], None] = '381bf2cbe990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_offer_available', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('offer_coupon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'offer_coupon_code')
    op.drop_column('products', 'is_offer_available')
    # ### end Alembic commands ###
