"""add_offer_fields_to_product

Revision ID: 3306be9f287f
Revises: 381bf2cbe990
Create Date: 2026-09-10 15:55:55.856053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3306be9f287f'
down_revision: Union[str, Sequence[str], None] = '381bf2cbe990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_offer_available', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('offer_coupon_code', sa.String(length=50), nullable=True))
    op.drop_column('products', 'care_instructions')
    op.drop_column('products', 'video_url')
    op.drop_column('products', 'stone_type_static')
    op.drop_column('products', 'stone_weight')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'finish')
    op.drop_column('products', 'hover_image')
    op.drop_column('products', 'short_desc')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'is_hallmarked')
    op.drop_column('products', 'has_certificate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('has_certificate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_hallmarked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('weight', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('short_desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('hover_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('finish', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('low_stock_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stone_weight', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stone_type_static', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('care_instructions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('products', 'offer_coupon_code')
    op.drop_column('products', 'is_offer_available')
    # ### end Alembic commands ###
