"""Add UI fields to product

Revision ID: 381bf2cbe990
Revises: 25abb6f044e7
Create Date: 2026-09-09 15:55:33.736071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381bf2cbe990'
down_revision: Union[str, Sequence[str], None] = '25abb6f044e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('short_desc', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('care_instructions', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('hover_image', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('video_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('weight', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('finish', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('stone_type_static', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('stone_weight', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('is_hallmarked', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('has_certificate', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'has_certificate')
    op.drop_column('products', 'is_hallmarked')
    op.drop_column('products', 'stone_weight')
    op.drop_column('products', 'stone_type_static')
    op.drop_column('products', 'finish')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'video_url')
    op.drop_column('products', 'hover_image')
    op.drop_column('products', 'care_instructions')
    op.drop_column('products', 'short_desc')
    # ### end Alembic commands ###
