"""remove target_audience and use collections

Revision ID: 4c43a8780250
Revises: bda3897cfad2
Create Date: 2026-09-10 11:20:07.071848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c43a8780250'
down_revision: Union[str, Sequence[str], None] = 'bda3897cfad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data migration: Ensure collections exist
    op.execute("INSERT INTO collections (name) VALUES ('Women''s Collection') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO collections (name) VALUES ('Men''s Collection') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO collections (name) VALUES ('Kids Collection') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO collections (name) VALUES ('Religious') ON CONFLICT DO NOTHING")

    # Data migration: Map target_audience to collections
    op.execute("""
        INSERT INTO product_collections (product_id, collection_id)
        SELECT p.id, c.id
        FROM products p
        JOIN collections c ON
            (p.target_audience = 'WOMENS' AND c.name = 'Women''s Collection') OR
            (p.target_audience = 'MENS' AND c.name = 'Men''s Collection') OR
            (p.target_audience = 'KIDS' AND c.name = 'Kids Collection') OR
            (p.target_audience = 'RELIGIOUS' AND c.name = 'Religious')
        ON CONFLICT DO NOTHING
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'target_audience')
    
    # Also drop the ENUM type since it's no longer used by sqlalchemy
    op.execute("DROP TYPE IF EXISTS targetaudienceenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('target_audience', postgresql.ENUM('WOMENS', 'MENS', 'KIDS', 'RELIGIOUS', name='targetaudienceenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
