"""add demographic fields to user

Revision ID: 69929a42ba22
Revises: 9db6605b71df
Create Date: 2026-09-01 11:34:19.363676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69929a42ba22'
down_revision: Union[str, Sequence[str], None] = '9db6605b71df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('anniversary_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anniversary_date')
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'dob')
    # ### end Alembic commands ###
