"""Initial metal_rates table

Revision ID: bfb871cf1e59
Revises: 
Create Date: 2026-07-24 14:37:19.516464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb871cf1e59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_name', sa.String(length=50), nullable=False),
    sa.Column('metal_type', sa.String(length=20), nullable=False),
    sa.Column('purity', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metal_rates_id'), 'metal_rates', ['id'], unique=False)
    op.create_index(op.f('ix_metal_rates_metal_name'), 'metal_rates', ['metal_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metal_rates_metal_name'), table_name='metal_rates')
    op.drop_index(op.f('ix_metal_rates_id'), table_name='metal_rates')
    op.drop_table('metal_rates')
    # ### end Alembic commands ###
