"""Add KYC fields to User

Revision ID: c82599dc6ab6
Revises: bfe27fa2e3c1
Create Date: 2026-09-01 10:41:24.202548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82599dc6ab6'
down_revision: Union[str, Sequence[str], None] = 'bfe27fa2e3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('aadhar_number', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aadhar_number')
    op.drop_column('users', 'pan_number')
    # ### end Alembic commands ###
